# Geral configuration
general:
  cache_directory: cache
  datasets_directory: datasets



# Datasets configuration
datasets:
  
  ml-latest-small:
    source: https://files.grouplens.org/datasets/movielens/ml-latest-small.zip
    module: src.datasets.movielens_dataset
    class: MovielensDataset


# Optional: the 'paths' section define key directories where used in the project.
#paths:
#  # datasets:
#  datasets: custom_datasets_path
#  # cache: quick-access cache for files downloaded from the internet.
#  cache: custom_cache_path
#  # models: store trained models.
#  models: custom_models_path
#  # logs: store log files.
#  logs: custom_logs_path
